# Generated by Django 3.2.13 on 2022-05-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('slug', models.SlugField(unique=True, verbose_name='url-адрес жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Game Title')),
                ('description', models.TextField(blank=True, verbose_name='Game Description')),
                ('year', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Creation Year')),
                ('image', models.ImageField(blank=True, upload_to='games/', verbose_name='Game Image')),
                ('genre', models.ManyToManyField(blank=True, related_name='games', to='api.Genre', verbose_name='Genres')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
