# Generated by Django 3.2.13 on 2022-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Game Price'),
        ),
    ]
