# Generated by Django 3.2.13 on 2022-06-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220530_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='News Title')),
                ('post', models.TextField(verbose_name='Post Description')),
                ('post_image', models.ImageField(blank=True, upload_to='posts/', verbose_name='Post Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='api.game', verbose_name='Related game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
